### ISSUE TITLE
question

### ISSUE THREAD

**Issue by TheOneAndOnlyBRH** [scwmake/Supercell-Tools#1]
is there any lib/tool to re-compire assests to .sc ? or _tex.sc

**Comment by Daniil-SV** [comment]
For some big or complex projects you can use [this](https://github.com/scwmake/Supercell-Tools/tree/1e17f3b9a728fada3b7bb86031065e32377d65c2/SupercellFlash) C++ library. You can find an example of "recompilation" in [this](https://github.com/scwmake/Supercell-Tools/blob/1e17f3b9a728fada3b7bb86031065e32377d65c2/Tests/SupercellFlash/main.cpp) file.
Also, if you need it for some small and fast tasks, then you can use [node.js bindings](https://github.com/scwmake/SupercellSWF-JS). C++ library and bindings have the same api with minor adjustments for node.js api
